apiVersion: v1
kind: Secret
metadata:
    name: postgres-zitadel
    namespace: zitadel
data:
    admin-password: ENC[AES256_GCM,data:ng3zpSJU5lrLFvpVDCi3B5lNKMuJ7VJvhYzZEVATXj4Qqb5w2gGtP+VCKp7Z0X+/DR4AZzNupVl+q+Q=,iv:/cwRe/LaPSKGtKk/7lJl+f3TSMJsIIcAyKHgz6vLfSs=,tag:RsoL6Lh/cWCjZGX/7NN1LQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q3ykcmr4sku3lxdplhs6astxwdlwq5qlv259l2sl5e4x0guyt3ysps69gu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKcjl5VXVWd0ZQTElRRDh4
            UlRQZVVXSGxzSHE0MlhGSlcxeWlHVWEydVFNClB0aC9BMnJtLzNOLytKS0ZaTUhZ
            UXF3bUVVMjdaZ3IvS3dYME5ULzJrVmcKLS0tIGd5Tld3by90NENETnFNc3ZxY2xr
            TjhnWC9nQWdJcDFGVW5lU1B5bzVNdHcKh5AyHmBQbUNdsZKYCQX231YfyTNDIIYm
            0qiYGwW+rpl/bdc7gzNSKdk29Wn4zolKn5tXyOZwWHAr/7Fsbk4TLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T17:14:57Z"
    mac: ENC[AES256_GCM,data:1Nch7WKJwQom5flDOMEtNmth8hWWRjY7IxtjPoOeoM75ojdIxFCgJQgpjhXOu7aZeeJ1Z5rTmBtMN9tunxRGOEORrK/sr5m9wm9fZIjcFgFAV3xPTw7MVdV8+qLG4QS7urxhr5o247y//IPpF6KmzOzF4anp70dptT6up1m19fU=,iv:JCeT+QCV3Zt1P0A2bsIyHbZT+k4rHVpo4MftxYWbM4w=,tag:Q2wpQKcpdJ/W6ztosFszBA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
