# Generate a sample secret
apiVersion: v1
kind: Secret
metadata:
    name: secret-test
    namespace: default
type: Opaque
data:
    password: ENC[AES256_GCM,data:ZEXoDHh3E4c9vel7,iv:Z04oGV1C+qXZuB5VIla0NQ2IiaRuQGH8eeAZ6rYKFQU=,tag:UdT3vK+v3CZPUMuy+QO8fw==,type:str]
    username: ENC[AES256_GCM,data:wMJfaxet5hcp1Ibe,iv:YrcMG5C1GNypstQCg41xhphVAn5/0gEiMqmbRzmd3z0=,tag:sXWaxiDKtYdoqTTIpU7EfQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q3ykcmr4sku3lxdplhs6astxwdlwq5qlv259l2sl5e4x0guyt3ysps69gu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3bjhXQ3pxNWVaZE5najdz
            cE5PZklQNTlZZi92SjlvWTBlYkRna1VHREVZCit2L2ZraUYyRGNoa3llVmE3Tmdy
            MFFBeThZK2JDREk1WnNSQWhzSVl0WHcKLS0tIHVuejA2L2JxYjRNYzNYZGpnako5
            YlVSL3A3ZkpwMHhBbm1yajVmcUJENUUKeBpmJpYVMmoqi76+9Tk5cqmBBxzD1QtH
            FP7PXU3jFxrBg+V0StPkLomuaE5yD1WSQhejxB6ZmTaK44qCz8UrBQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-16T22:09:57Z"
    mac: ENC[AES256_GCM,data:EogBWPbngdilnYwictTOJ3UknmXVA91tdqGH45XPKmXYNa+toYP0pYMV1I3LWcxarRPGntl5P519Z6NjMF8SS1iYiTFM0vJwV3BEBbDbxMKN/PuZHoLoMHZwokLzXtFQnJHEsu2dP+gTie+h7TBkjp2auDNylucr8zFZHf3fLMk=,iv:JEtmE6InK0puOK4XEIRl2DKi8MgnVIsqW7QAH+Uhn14=,tag:nKvjGL1kU8RNVjsf6D/UgA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
