apiVersion: v1
kind: Secret
metadata:
  name: zitadel-zitadel
  namespace: zitadel
data:
  masterkey: dmF1bHQ6c2VjcmV0L2RhdGEveml0YWRlbC9wZyNtYXN0ZXJrZXk=
  config-yaml: |
    Database:
      Postgres:
        User:
          Password: "${vault:secret/data/zitadel/pg#password_user}"
        Admin:
          Password: "${vault:secret/data/zitadel/pg#password_admin}"
