apiVersion: v1
kind: Secret
metadata:
    name: zitadel-zitadel
    namespace: zitadel
data:
    masterkey: ENC[AES256_GCM,data:lMfvzcweiNzRTjxP34iED+hH1CxER7il0D+rYk4vH/eAb2MLnkfGyGInfWc=,iv:A6ZNJd71s+5JD2K29Xa2XrqRQrk8gb45pK+g80scOLw=,tag:/+Dr8Q6VL65ARAevAxXYhw==,type:str]
    config-yaml: ENC[AES256_GCM,data:cpxfTLX7WZlpSXSKlibZbSoiN/ci3F0jIT2TnfppeJdziq1sH8WDnNeD5COFnAiZGpkzciKYoA6+tyrL5dDYtKlEq8rvHgkpPY8cVf3yJMxmm2N7Bo2jO9qOkdVOEysME5+TWOqNFbCgFtQC5pqgZP/lM8o23lXFqgVm+cdPdVCMnAoC7TVtHu7sBoAmVdkvqqLCD3QRU/i8AuM81mSInjaEnuq7Xz/oeSgGXrD5EEznr1zQ3n0golF8eVXPwRbY3Q==,iv:VwCZuRSxAHoPRKiVig7LAZ4F8NoWJ9sc1oZTvAgT9K4=,tag:L70dMREDFkzhtQ8BkRuGnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1q3ykcmr4sku3lxdplhs6astxwdlwq5qlv259l2sl5e4x0guyt3ysps69gu
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBLcWFnNFlYcHNxaHAzU3dG
            ZzZVSVk1QzdOY1EzVHhYTldEN0JIbzJHWlhzCldyVWdoamF3dm5rZnM0ZXlyUjJH
            dEZTWnZ0bjNFUGFvMWhLLzFGcnI2dFEKLS0tIFFUcFhFcEM2UjRIRXE2VDdvT0dU
            N2JrMExZbUI2RXVTdVZwcDdha1FzbTAKwauopI/tUYXdqV/gQqoAKIQg8Y+E7M4p
            OA1HaV7FXCr9Jy7g2yNqceKaz7aqH87GWeVZaBeg9SxUyYIP8R/MTA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-19T17:15:04Z"
    mac: ENC[AES256_GCM,data:3u9iUJYRKQ6sJtO4UNmdBf/tMK8RpeAx9ifYsgbqNDmPKpjWqwtDHvhmOqRm1B1c2GeZ/OFuvU8BYUsbvjfq52Y0ikypfGHQ4dJJevOucAk/oMJ3heTTvpbI+ssAP20IzS8FEawjb54Y08eiQEmKVOQ2KJMZAdG1wWyJ4xN8q00=,iv:rHQ5haFL3fCuHBbSp3q2zrtuIkqarixAvHS5KTQmeHs=,tag:FYY4mRc7NSsCgKP+4wdCRw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.0
