apiVersion: v1
kind: Secret
metadata:
  name: zitadel-zitadel
  namespace: zitadel
data:
  masterkey: eDEyMzQ1Njc4OTAxMjM0NTY3ODkwMTIzNDU2Nzg5MXk=
  config-yaml: |
    Database:
      Postgres:
        User:
          Password: "8JtpAXjfuTKjZ9nPxyS6FjMF3eBexq1ICWEo1TDsotNkA"
        Admin:
          Password: "ySqbsmbvvF9R2IVCFgGakbwyEizFJKGup17fSR8Xmt6FGPaE"
