apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: traefik
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: traefik
    repoURL: https://traefik.github.io/charts
    targetRevision: 32.1.1
    helm:
      releaseName: traefik
      valuesObject:
        ingressRoute:
          dashboard:
            enabled: true
        metrics:
          prometheus:
            service:
              enabled: true
            disableAPICheck: false
            serviceMonitor:
              enabled: true
              metricRelabelings:
              - sourceLabels: [__name__]
                separator: ;
                regex: ^fluentd_output_status_buffer_(oldest|newest)_.+
                replacement: $1
                action: drop
              relabelings:
              - sourceLabels: [__meta_kubernetes_pod_node_name]
                separator: ;
                regex: ^(.*)$
                targetLabel: nodename
                replacement: $1
                action: replace
              jobLabel: traefik
              interval: 30s
              honorLabels: true
            prometheusRule:
              enabled: true
              rules:
              - alert: TraefikDown
                expr: up{job="traefik"} == 0
                for: 5m
                labels:
                  context: traefik
                  severity: warning
                annotations:
                  summary: "Traefik Down"
                  description: "{{ $labels.pod }} on {{ $labels.nodename }} is down"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: traefik
