apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ""
    server: ""
  name: Weebo3
contexts:
- context:
    cluster: Weebo3
    user: Weebo3
  name: Weebo3
current-context: Weebo3
kind: Config
preferences: {}
users:
- name: Weebo3
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - oidc-login
      - get-token
      - --oidc-issuer-url=https://login.weebo.fr
      - --oidc-client-id=
      - --oidc-extra-scope="email offline_access profile openid"
      - --grant-type=authcode
      command: kubectl
      env: null
      provideClusterInfo: false
