version: '3'

env:
  KUBECONFIG: "./kubeconfig.yaml"
  ARGO_APP_REPO: "https://github.com/batleforc/Weebo4GitOps"
  ARGO_DEST_SERVER: "https://kubernetes.default.svc"
  ARGO_VERSION: "7.6.10"

includes:
  argo:
    taskfile: 0.task/argocd/argo.yaml
  sops:
    taskfile: 0.task/sops/taskfile.yaml
  cilium:
    taskfile: 0.task/cilium/taskfile.yaml
  vault:
    taskfile: 0.task/vault/taskfile.yaml
  tf:
    taskfile: 0.task/terraform/taskfile.yaml

tasks:
  hello:
    cmds:
    - echo "Hello World"
  kubectl:
    cmds:
    - kubectl {{ .CLI_ARGS }}

