version: '3'

env:
  KUBECONFIG: "./kubeconfig.yaml"
  ARGO_APP_REPO: "https://github.com/batleforc/Weebo4GitOps"
  ARGO_DEST_SERVER: "https://kubernetes.default.svc"
  ARGO_VERSION: "7.6.10"

includes:
  argo:
    taskfile: 0.task/argocd/argo.yaml
  sops:
    taskfile: 0.task/sops/taskfile.yaml
  cilium:
    taskfile: 0.task/cilium/taskfile.yaml
  vault:
    taskfile: 0.task/vault/taskfile.yaml
  tf:
    taskfile: 0.task/terraform/taskfile.yaml
  ansible:
    taskfile: 0.task/ansible/taskfile.yaml

tasks:
  hello:
    cmds:
    - echo "Hello World"
  kubectl:
    cmds:
    - kubectl {{ .CLI_ARGS }}
  kubectl-oidc:
    cmds:
    - kubectl {{ .CLI_ARGS }} --kubeconfig kubeconfig.oidc.yaml
  traefik:
    cmds:
    - task kubectl --  port-forward $(task kubectl -- get pods --selector "app.kubernetes.io/name=traefik" --output=name -n traefik) -n traefik 9000:9000
  create-kubeconfig-oidc:
    vars:
      OIDC_CLIENT_ID:
        sh: task kubectl -- get secret -n zitadel cluster-auth -o jsonpath='{.data.clientID}' | base64 -d
      server_url:
        sh: cat kubeconfig.yaml | yq .clusters[0].cluster.server
      server_ca:
        sh: cat kubeconfig.yaml | yq .clusters[0].cluster."certificate-authority-data"
    cmds:
    - cp kubeconfig.oidc-template.yaml kubeconfig.oidc.yaml
    - yq e -i '.users[0].user.exec.args[3] = "--oidc-client-id={{ .OIDC_CLIENT_ID }}"' kubeconfig.oidc.yaml
    - yq e -i '.clusters[0].cluster.server = "{{ .server_url }}"' kubeconfig.oidc.yaml
    - yq e -i '.clusters[0].cluster."certificate-authority-data" = "{{ .server_ca }}"' kubeconfig.oidc.yaml

