apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-zitadel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.0.3
    helm:
      releaseName: pgsql-zitadel
      valuesObject:
        volumePermissions:
          enabled: true
        tls:
          enabled: true
          certificatesSecret: postgres-cert
          certFilename: "tls.crt"
          certKeyFilename: "tls.key"
        auth:
          existingSecret: postgres-zitadel
          secretKeys:
            adminPasswordKey: "admin-password"
        primary:
          annotations:
            vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
            vault.security.banzaicloud.io/vault-role: "default"
            vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
            vault.security.banzaicloud.io/vault-path: "kubernetes"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zitadel
