apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: zitadel-zitadel
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: zitadel
    repoURL: https://charts.zitadel.com
    targetRevision: 8.5.0
    helm:
      releaseName: zitadel-zitadel
      valuesObject:
        zitadel:
          masterkeySecretName: zitadel-zitadel
          configSecretName: zitadel-zitadel
          configmapConfig:
            ExternalSecure: true
            ExternalDomain: "login.weebo.fr"
            Tracing:
              Type: "otel"
            Telemetry:
              Endpoints: "http://tempo.monitoring.svc.cluster.local:4317"
              Enabled: true
            TLS:
              Enabled: false
            FirstInstance:
              Org:
                Machine:
                  Machine:
                    Username: "zitadel-admin-sa"
                    Name: "Admin"
                  MachineKey:
                    Type: 1
            Database:
              postgres:
                Host: pgsql-zitadel-postgresql
                Port: 5432
                Database: zitadel
                MaxOpenConns: 20
                MaxIdleConns: 10
                MaxConnLifetime: 30m
                MaxConnIdleTime: 5m
                User:
                  Username: zitadel
                  SSL:
                    Mode: verify-full
                Admin:
                  Username: postgres
                  SSL:
                    Mode: verify-full
          dbSslCaCrtSecret: postgres-cert
          dbSslAdminCrtSecret: postgres-cert
          dbSslUserCrtSecret: zitadel-cert
        servuceAccount:
          name: default
          create: false
        podAnnotations:
          vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
          vault.security.banzaicloud.io/vault-role: "default"
          vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
          vault.security.banzaicloud.io/vault-path: "kubernetes"
          vault.security.banzaicloud.io/vault-agent: "true"
        ingress:
          enabled: true
          annotations:
            kubernetes.io/ingress.class: "traefik"
            cert-manager.io/cluster-issuer: "letsencrypt-prod"
            haproxy-ingress.github.io/timeout-client: 180s
            haproxy-ingress.github.io/proxy-body-size: 512m
            haproxy-ingress.github.io/backend-protocol: h2
          hosts:
          - host: "login.weebo.fr"
            paths:
            - path: /
              pathType: ImplementationSpecific
              backend:
                service:
                  name: zitadel
                  port:
                    number: 8080
          tls:
          - hosts:
            - login.weebo.fr
            secretName: login-weebo-tls
        initJob:
          podAnnotations:
            vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
            vault.security.banzaicloud.io/vault-role: "default"
            vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
            vault.security.banzaicloud.io/vault-path: "kubernetes"
            vault.security.banzaicloud.io/vault-agent: "true"
        setupJob:
          podAnnotations:
            vault.security.banzaicloud.io/vault-addr: "https://vault.vault:8200"
            vault.security.banzaicloud.io/vault-role: "default"
            vault.security.banzaicloud.io/vault-tls-secret: "vault-tls"
            vault.security.banzaicloud.io/vault-path: "kubernetes"
            vault.security.banzaicloud.io/vault-agent: "true"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: zitadel
