apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-webhook
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: vault-secrets-webhook
    repoURL: ghcr.io/bank-vaults/helm-charts
    # https://github.com/bank-vaults/vault-operator/pkgs/container/helm-charts%2Fvault-secrets-webhook
    targetRevision: 1.21.3
    helm:
      releaseName: vault-webhook
  destination:
    server: "https://kubernetes.default.svc"
    namespace: vault-infra
