---
apiVersion: v1
kind: Service
metadata:
  name: dns-server
  namespace: outdns
  labels:
    app: dns-server
  annotations:
    lbipam.cilium.io/sharing-key: "weebo3-gate"
    lbipam.cilium.io/ips: "37.187.142.160"
    # io.cilium/lb-ipam-sharing-key: "weebo3-gate"
    # io.cilium/lb-ipam-ips: 37.187.142.160
spec:
  ports:
    - name: tcp
      protocol: TCP
      port: 53
      targetPort: 53
    - name: loop
      protocol: TCP
      port: 953
      targetPort: 953
    - name: udp
      protocol: UDP
      port: 53
      targetPort: 53
  selector:
    app: dns-server
  type: LoadBalancer
