apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infra-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/batleforc/Weebo4GitOps'
    path: infra/secret
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
