operator:
  replicas: 1
ipam:
  operator:
    clusterPoolIPv4PodCIDRList: 10.42.0.0/16
    clusterPoolIPv6PodCIDRList: fd00::/104
ipv4NativeRoutingCIDR: 10.42.0.0/16
ipv6NativeRoutingCIDR: fd00::/104
ipv4:
  enabled: true
ipv6:
  enabled: true
loadBalancer:
  mode: dsr
kubeProxyReplacement: true
routingMode: native
autoDirectNodeRoutes: true
hubble:
  relay:
    enabled: true
  ui:
    enabled: true
l2announcements:
  enabled: true
