apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: outdns
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://git.weebo.fr/sandbox/gitops-local'
    path: 'infra/helm/outdns'
    helm:
      releaseName: outdns
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: outdns
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
