apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- serviceaccount.yaml
- terraform-pvc.yaml
- terra.yaml

configMapGenerator:
- name: terraform-login
  namespace: zitadel
  files:
  - terraform/main.tf
  - terraform/user.tf
  - terraform/grafana.tf
  - terraform/harbor.tf
  - terraform/cluster.tf
  - terraform/vault.tf
generatorOptions:
  disableNameSuffixHash: true
