---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: terraform-apply
  namespace: zitadel
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: terraform-secret
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "pods", "daemonsets"]
    verbs: ["get", "list", "watch", "patch"]
  - apiGroups: ["*"]
    resources: ["namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: terraform-apply-binding
subjects:
  - kind: ServiceAccount
    name: terraform-apply
    namespace: zitadel
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: terraform-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: terraform-apply-secret
  namespace: zitadel
  annotations:
    kubernetes.io/service-account.name: terraform-apply
type: kubernetes.io/service-account-token
