kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: terra-job
  namespace: zitadel
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-path
