apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: crds-prom
  namespace: argocd
spec:
  project: default
  syncPolicy:
    automated: {}
  source:
    chart: prometheus-operator-crds
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 5.1.0
    helm:
      releaseName: crds-prom
  destination:
    server: "https://kubernetes.default.svc"
    namespace: monitoring
